modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/MightyPirates/Scannable/issues"
license = "MIT"

[[mods]]
modId = "scannable"
version = "${file.jarVersion}"
displayName = "Scannable"
displayURL = "https://github.com/MightyPirates/Scannable"
logoFile = "logo.png"
authors = "Sangar"
description = '''
Scan the area for points of interest.
'''

[[dependencies.scannable]]
modId = "forge"
mandatory = true
versionRange = "[40.0.40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.scannable]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
