modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/MightyPirates/Scannable/issues"
license = "MIT"

[[mods]]
modId = "scannable"
version = "${file.jarVersion}"
displayName = "Scannable"
displayURL = "https://github.com/MightyPirates/Scannable"
logoFile = "logo.png"
authors = "Sangar"
description = '''
Scan the area for points of interest.
'''

[[dependencies.scannable]]
modId = "forge"
mandatory = true
versionRange = "[43.1.15,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.scannable]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.2)"
ordering = "NONE"
side = "BOTH"
